import luigi
import os
# Module generated by ariadne on 2016-03-03 13:24:05.763410
class teststage2(luigi.Task):
    DIR=luigi.Parameter()
    FILENAME=luigi.Parameter()
    def requires(self):
        return 
    def output(self):
        return
    def run(self):
        os.spawnlp(os.P_WAIT, './touchfile.sh', './touchfile.sh', self.DIR, self.FILENAME)
        return
    def complete(self):
        return 1
