import luigi
import os
# Module generated by ariadne on 2016-03-03 11:54:38.570921
class teststage1(luigi.Task):
	DIR=luigi.Parameter()
	def requires(self):
		return 
	def output(self):
		return
	def run(self):
		os.spawnlp(os.P_WAIT, 'mkdir', 'mkdir', self.DIR)
		return
	def complete(self):
		return 1
