import luigi
import os
# Module generated by ariadne on 2016-03-04 10:18:50.875301
class teststage1(luigi.Task):
    drname=luigi.Parameter()
    def requires(self):
        return 
    def output(self):
        return luigi.LocalTarget(self.drname)
    def run(self):
        print("Dirname:"+self.drname)
        os.spawnlp(os.P_WAIT, 'mkdir', 'mkdir', self.drname)
        return
# Module generated by ariadne on 2016-03-04 10:18:50.875398
class teststage2(luigi.Task):
    dirname=luigi.Parameter()
    filename=luigi.Parameter()
    def requires(self):
        return teststage1(self.dirname)
    def output(self):
        return 
    def run(self):
        os.spawnlp(os.P_WAIT, './touchfile.sh', './touchfile.sh', self.dirname, self.filename)
        return
