# generated by shell2pipe on 2016-03-15
import os
import plugin

plugin_class='cp1'


class cp1(plugin.AriadneOp):
    name='cp1'


    def run(self, args):
        os.system('cp tmp/yarr tmp/yarr1')
