# generated by shell2pipe on 2016-03-15
import os
import plugin

plugin_class='touch1'


class touch1(plugin.AriadneOp):
    name='touch1'


    def run(self, args):
        os.system('touch tmp/yarr')
