# generated by shell2pipe on 2016-03-17
import os
import plugin

plugin_class='cpstuff'


class cpstuff(plugin.AriadneOp):
    name='cpstuff'


    def run(self, args):
        os.system('cp stuff/contents stuff/otherstuff')
        os.system('cp stuff/contents morestuff/')
