# generated by shell2pipe on 2016-03-17
import os
import plugin

plugin_class='mkdirs'


class mkdirs(plugin.AriadneOp):
    name='mkdirs'


    def run(self, args):
        os.system('mkdir stuff')
        os.system('mkdir stuff/otherstuff')
        os.system('mkdir morestuff')
