# generated by shell2pipe on 2016-03-17
import os
import plugin

plugin_class='touchstuff'


class touchstuff(plugin.AriadneOp):
    name='touchstuff'


    def run(self, args):
        os.system('touch stuff/contents')
