# Generated by ariadne on 2016-03-15.
import luigi
import os
class touch1_l(luigi.Task):
    def requires(self):
        return
    def run(self):
        os.system('ariadne.py runplugin touch1 testp')
