# Generated by ariadne on 2016-07-11.
import luigi
import os
class add_l(luigi.Task):
    def run(self):
        os.system('ariadne.py runplugin mkdirs plugins dirs=['a', 'b'] ')
        os.system('ariadne.py runplugin mkfiles plugins contents=['1', '2'] filenames=['a/a.txt', 'b/b.txt'] ')
        os.system('ariadne.py runplugin mkdirs plugins dirs=['c'] ')
       os.system('ariadne.py runplugin add plugins')
